Redesign Login/Authentication System (#8)
* Changed Input, Login, ThemeContext, Form, and (#7)

themes.js. Also added companyLogo.png. Main
change is global color theme and login page
changed.

* Current chanes??

* Almost done....

I'm getting an error saying "Phone number is missing for user". It also doesn't crash now!

* Some changes???

* WAIT THE CODE ACTUALLY WORKS??

FUCK THIS SHIT.
I HATE GOOGLE.
I HATE THE INTERNET.
THIS IS BULLSHIT.

I SPENT OVER 5 HOURS ON THIS.
NOBODY COULD HELP ME -- NOT EVEN GOD.

THIS SHIT ONLY WORKS IF AUTH IS PASSED AS THE FIRST PARAM, OTHERWISE IT BREAKS. THE ERROR CODES IT GIVES OUT OTHERWISE ARE BULLSHIT.

JFC.

I HATE CODING.

* Removed TwoFa.js references

Need so I can build and deploy.
Am getting error: [Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (pat, line 0)

* Small change, code doesn't verify

* Testing some changes

* More minor changes

Tested the code, get this error code: [Error] Error verifying the code: – TypeError: e._process is not a function. (In 'e._process(n,o)', 'e._process' is undefined) — mfa_resolver.ts:72
TypeError: e._process is not a function. (In 'e._process(n,o)', 'e._process' is undefined) — mfa_resolver.ts:72
	(anonymous function) (main.d03d502a.js:845:4266)

* 2FA SMS LOGIN DONE

WHAT A SHITSHOW OF A CODEBASE TO DO THIS IN.

Now, if the user wishes to login, they must use 2FA if available. This has not been tested on those without 2FA, but Chat says that it should work.

Now, I have to start modifying the code so that it actually looks aesthetic! (Per Mias standards...)

Things to fix:
-Make it look aesthetic.
-Once the user logs in, they are AUOMATICALLY sent an SMS. The button to generate a new one will be blocked for 30 seconds with a countdown, at which they will have the option to request a new code once again.

I am so happy that this shit worked, you don't even know!!!!!!!!!!

* Added minor comments

* Updated Initial styling

Will need to reintroduce the comments once again...

Also, The input code button looke ASS im so sorry ethan.

I will change it soon, i pwomise

* Install react-bootstrap, begin changes.

* Bootstrap works!

Will need to change how the CSS is applied later.... Probably in index.js....

* Changed logo for screen size

THE LOGO IS not centered PERFECTALLY.

* Added 2FA back in!

Now, I just need to style it!

* Finished Login.CSS****

Well.. The styles are hard coded since I was tired and din't want to make everything connected to JS from the CSS file.

I'll do that once we have finalized the Auth System....

* SMS 2FA For Signup Works!

Now let me just style and make sure it works on mobile....

* CSS for signup mostly done

Just need to fix the hexagon for the form

* Cannot get it to work.....

Pls help

* Change ESLint Rules

Because sometimes we have unused Vars for things that will be implemented later

---------

Co-authored-by: Ethan Tarrer <106130927+asneakypanda@users.noreply.github.com>